version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.6.1
    working_directory: ~/zappa-ex

    steps:
      - checkout
      - restore_cache:  # ensure this step occurs *before* installing dependencies
          key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install pipenv
            pipenv install
      - save_cache:
          key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - ".venv"
            - "/usr/local/bin"
            - "/usr/local/lib/python3.6/site-packages"
  deploy:
    docker:
      - image: circleci/python:3.7-stretch
    working_directory: ~/zappa-ex
    steps:
      - checkout
      - run:
          name: Install zappa
          command: pip install zappa
      - run:
          name: Install pipenv
          command: pip install pipenv
      - run:
          name: Install dependencies
          command: pipenv install
      - run:
          name: show contents
          command: ls
      - run:
          name: Deploy to aws with zappa, try to update if exists
          command: pipenv run zappa update dev || pipenv run zappa deploy dev

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master