version: 2
jobs:
  # build job omitted for brevity
  deploy:
    docker:
      - image: circleci/python:3.7-stretch
    working_directory: ~/circleci-docs
    steps:
      - run:
          name: Install zappa
          command: pip install zappa
      - run:
          name: Deploy to aws with zappa, try to update if exists
          command: zappa update dev || zappa deploy dev

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master